server:
  #默认端口8080，此处可以修改端口号
  port: 8888

datasource:
  url: jdbc:mysql://81.68.92.238:3306/bugly?useUnicode=true&characterEncoding=UTF-8
  password: test
  driver-class-name: com.mysql.jdbc.Driver
  username: root