server:
  #默认端口8080，此处可以修改端口号
  port: 8888

datasource:
  url: jdbc:mysql://10.1.120.172:3306/member_club_test?useUnicode=true&characterEncoding=UTF-8
  password: wdbuyer.123456
  driver-class-name: com.mysql.jdbc.Driver
  username: root